<a href="https://colab.research.google.com/github/nicolecosta/nlu/blob/main/IntRecV2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Prerequisites**

In [ ]:
!pip install "tensorflow-text==2.8.*"

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.9 MB 6.5 MB/s 


In [ ]:
import tensorflow_hub as hub
import numpy as np
from tensorflow_text import SentencepieceTokenizer
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
import tensorflow as tf

In [ ]:
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3")

In [ ]:
database = pd.read_csv("tfhubdatasett4.csv",sep=";")

print(database.shape)
database.head()

(16, 2)


message   intent
0                                    oi    greet
1                        olá, tudo bem?    greet
2                          Oie, beleza?    greet
3                                   Eai    greet
4  Eu queria saber como tá o tempo hoje  weather

In [ ]:
msg2 = "olá, bom dia"
print(embed(msg)[0][0:512])

tf.Tensor(
[ 5.32772280e-02 -4.55587022e-02  8.19604471e-03 -6.44541159e-02
  5.09206764e-02 -7.35339224e-02  3.04773659e-03 -4.05600108e-02
 -3.60104851e-02 -5.54719381e-02 -4.07539047e-02 -4.89074253e-02
  1.72561165e-02 -3.34558338e-02  4.53269742e-02  6.80100056e-04
  1.65544711e-02 -1.60089824e-02 -1.97091084e-02 -2.91748773e-02
 -2.33390015e-02 -1.37028657e-02 -6.92512188e-03 -3.23525965e-02
  3.30801532e-02  2.50285380e-02  1.61077715e-02  1.78410206e-02
 -1.03677325e-01 -5.95322344e-03 -5.01959212e-02 -9.03524738e-03
  5.26192971e-02 -3.26984003e-02 -9.15941224e-03 -1.09446518e-01
 -6.81101158e-02 -4.97875139e-02  2.20443737e-02  6.02079481e-02
  1.14528630e-02 -3.62761803e-02 -2.83641201e-02 -5.85538261e-02
  2.05865391e-02 -6.36158809e-02 -2.22964175e-02 -8.13204795e-03
  3.63187045e-02 -1.85456816e-02  2.66348012e-03 -6.08174689e-03
 -2.53820587e-02 -3.53035182e-02  2.87038181e-02 -6.81669787e-02
 -6.89025745e-02  3.09837442e-02  2.77426606e-03 -1.27973128e-02
  6.63829669e-

In [ ]:
  # embeddings = tf.TensorArray(tf.float32, size=0, dynamic_size=True, clear_after_read=False)
  # msg = tf.constant(['olá, bom dia'])
  # result = embed(msg)[0][0:512]
  # #results = np.array(result)
  # print(result)
  # embeddings.write(0,result)

tf.Tensor(
[ 0.02401914 -0.02005937 -0.00481457 -0.02166102  0.07007571  0.06336459
 -0.00760504  0.00129933  0.00366431  0.01204096  0.05903853 -0.09077695
  0.05553141 -0.00089129 -0.06202862  0.04126437  0.0713708   0.04911197
  0.02849547  0.00859556  0.03222981  0.01443902  0.0170525  -0.03614061
  0.03992437  0.01413525  0.04384405 -0.04089481 -0.06549767 -0.01306448
 -0.02208204 -0.00485581 -0.08447903 -0.07306918  0.02729711 -0.06167107
 -0.0259941  -0.02748876 -0.00408559 -0.04476449  0.07679211  0.02106631
 -0.03026249  0.02327908  0.00406091  0.05569045  0.01238389  0.10404773
  0.01564375  0.04325782  0.01769492 -0.02165387 -0.00220757 -0.00821008
 -0.05345159 -0.07984862 -0.06150847 -0.01290631  0.02885613 -0.02860809
  0.05331286 -0.03500737 -0.08727742 -0.01024987 -0.04428779 -0.01638058
 -0.02083313  0.00140058 -0.00870483  0.0381452   0.0057994   0.05269574
  0.02636022  0.00300184  0.0161561   0.03706812  0.04516131 -0.05062785
 -0.03569665 -0.01225666 -0.00745667 -0.

In [ ]:
columnmessage = database['message']
embeddings = tf.TensorArray(tf.float32, size=0, dynamic_size=True, clear_after_read=False)
#tentar com Series
for message in columnmessage:
  #print(message)
  msg = tf.constant(message)
  result = embed(msg)[0][0:512]
  #results = np.array(result)
  print(result)
  embeddings.write(0,result)

#embeddings = np.array(embeddings)
#print(results)
print(embeddings)
#len(embeddings)
#len(embeddings)


ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)  File "<ipython-input-50-64ce638f4971>", line 10, in <module>
    embeddings.write(0,result)  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 245, in wrapped
    error_in_function=error_in_function)
ERROR:tensorflow:=

tf.Tensor(
[ 4.80121002e-02  6.26051128e-02 -1.22022685e-02 -2.56004110e-02
 -5.87954232e-03 -1.11547345e-02 -2.85057649e-02 -8.54070261e-02
  6.96032308e-03 -2.32428312e-02 -2.36279368e-02 -5.55011723e-03
  3.36343329e-03  2.46568359e-02  7.21149743e-02  1.69200283e-02
  5.69832474e-02  9.86688398e-03 -5.23024052e-02  1.42694935e-02
  6.23172428e-03  1.92785840e-02 -2.86018779e-03  4.17079069e-02
  4.58691409e-03 -4.08431934e-03  2.08052266e-02 -5.51135791e-03
  1.79002639e-02 -5.75575866e-02 -1.92000456e-02 -1.81767698e-02
  1.29902354e-02 -8.68542418e-02 -2.68740952e-02 -6.02745675e-02
 -5.56590706e-02 -2.18457710e-02 -2.55347490e-02 -2.85451803e-02
  5.31172343e-02  1.44329444e-02 -6.08276203e-03 -4.81291413e-02
  1.11484490e-02 -6.92838430e-03  2.54523866e-02  4.26668748e-02
  5.79168946e-02 -4.71465662e-02 -2.76831370e-02 -6.61671907e-03
 -3.52222323e-02  1.03528250e-03 -1.05601015e-04 -1.61039399e-03
 -5.24249896e-02  8.89232103e-03 -3.62557396e-02  7.03304559e-02
  4.28918898e-

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)  File "<ipython-input-50-64ce638f4971>", line 10, in <module>
    embeddings.write(0,result)  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 245, in wrapped
    error_in_function=error_in_function)
ERROR:tensorflow:=

tf.Tensor(
[ 7.03398660e-02  7.65181109e-02 -1.90355200e-02 -2.28937455e-02
  3.03393397e-02  1.14394687e-02 -4.95951660e-02 -1.02706239e-01
 -4.48383689e-02 -2.27112155e-02 -1.35267209e-02 -1.42577551e-02
  3.53057049e-02  1.00636780e-02  1.65176392e-02  1.71743389e-02
  2.59344261e-02 -2.79112291e-02 -4.88245599e-02  2.67766658e-02
 -1.85003504e-02  5.42380698e-02 -3.87173221e-02  4.16710004e-02
 -7.19990162e-03  6.87349448e-03  1.59082524e-02 -3.82149443e-02
  4.49617542e-02 -1.47602474e-02 -3.40424255e-02 -1.95889045e-02
  9.12543852e-03 -9.81065929e-02 -1.04865506e-02 -2.66274679e-02
 -3.65701728e-02  9.66632366e-03 -4.57152985e-02 -2.45295893e-02
  7.27235377e-02 -5.25189377e-02 -4.45602946e-02 -6.01490438e-02
 -6.53845025e-03  2.30114534e-02  2.41113231e-02 -1.79210268e-02
  2.39005648e-02 -9.89625510e-03  2.31017303e-02 -3.69455367e-02
 -8.05843621e-02 -2.82413568e-02  2.14394573e-02  7.97743071e-03
  3.25973309e-03 -1.87863596e-02 -4.47467193e-02  4.67818119e-02
  3.64727452e-

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)  File "<ipython-input-50-64ce638f4971>", line 10, in <module>
    embeddings.write(0,result)  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 245, in wrapped
    error_in_function=error_in_function)
ERROR:tensorflow:=

tf.Tensor(
[ 0.02919818 -0.0550357   0.02981184  0.02402409 -0.04326492  0.00835366
 -0.07487892  0.06576042  0.01955951 -0.11350678  0.06853453 -0.00498336
 -0.07934852  0.0403858  -0.03669666  0.02596763  0.03950214  0.03060531
 -0.0399159  -0.08373861 -0.03355259  0.0549169   0.03677987 -0.01915918
  0.02858396  0.00665035  0.02394333 -0.01402307 -0.03426925  0.02503848
  0.03818472  0.04233194  0.04832966 -0.09155793  0.03403053  0.00231617
 -0.01400385 -0.00189572  0.06800631  0.04871736 -0.06222781  0.02447094
 -0.01518796  0.02213058 -0.07298559 -0.01875499 -0.05284783  0.00128174
  0.02436969 -0.04179567  0.07776314 -0.05498146  0.05346354 -0.04072047
 -0.01094136 -0.039962    0.02627471 -0.05876499  0.0264673   0.03109163
  0.02379807  0.00223379  0.01385684  0.03480693  0.02385012  0.04646794
  0.04073891  0.00488039 -0.04427899  0.09959406 -0.00694541  0.00309058
 -0.02580887 -0.06136551  0.10719013 -0.00193514  0.05636976 -0.08701079
  0.07930917  0.04906125 -0.04568607 -0.

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)  File "<ipython-input-50-64ce638f4971>", line 10, in <module>
    embeddings.write(0,result)  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 245, in wrapped
    error_in_function=error_in_function)
ERROR:tensorflow:=


tf.Tensor(
[-2.93948762e-02  1.66278481e-02 -1.75525695e-02 -1.91692654e-02
  1.20363310e-02 -4.78407554e-02 -3.92300859e-02 -5.50020263e-02
  2.91033834e-02 -9.24798995e-02 -9.09108073e-02 -9.24988240e-02
  2.83453427e-02  5.36603946e-03  5.14818542e-02  4.29240614e-02
 -7.73177296e-02  5.85554354e-02  3.09733618e-02  3.06734461e-02
  1.03011057e-02  9.64933634e-02  1.22035732e-02 -2.20251251e-02
 -1.12325354e-02  2.00006515e-02  1.37743847e-02 -5.54012768e-02
  3.78994420e-02 -3.57849225e-02  4.59674820e-02  3.21491063e-03
  5.05263992e-02 -6.30819574e-02  5.67789003e-02 -4.64999415e-02
 -2.59783715e-02  2.49479488e-02  9.27758403e-03  3.93989049e-02
 -9.44995321e-03 -2.22427398e-02 -6.33950457e-02 -5.27887605e-02
 -4.80618216e-02  3.60849462e-02 -7.58344606e-02 -5.97054102e-02
  2.91719753e-02 -2.26084366e-02 -5.35662994e-02 -7.84946606e-02
  1.33742075e-02 -6.58031404e-02 -5.37367575e-02 -3.46717089e-02
 -2.83978693e-02  3.27398218e-02  3.47865047e-03  4.56356853e-02
  1.56476181e

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)  File "<ipython-input-50-64ce638f4971>", line 10, in <module>
    embeddings.write(0,result)  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 245, in wrapped
    error_in_function=error_in_function)
ERROR:tensorflow:=

tf.Tensor(
[ 3.80038843e-02 -2.74689179e-02 -3.54251228e-02 -6.47920324e-03
 -7.66018331e-02 -1.35598127e-02  1.29474858e-02 -3.60164568e-02
 -3.68235670e-02 -6.16749674e-02 -7.33779669e-02 -3.92821729e-02
  3.53378169e-02 -3.65933753e-03  2.20329873e-02  4.10360657e-02
 -6.68364391e-02  4.67202179e-02  2.81927478e-03 -1.45094078e-02
 -4.76179011e-02  3.42302658e-02  7.18556531e-03 -1.00182509e-02
 -7.21768960e-02  3.89045067e-02 -2.07380541e-02 -7.62082040e-02
 -1.01877721e-02  3.74481417e-02  4.46341634e-02 -3.17246653e-02
  8.12224299e-02 -5.24432212e-02  2.04853583e-02 -5.42543456e-03
  4.65792082e-02 -1.98006667e-02  2.70605404e-02 -3.30005470e-03
 -4.69560958e-02 -2.74544470e-02 -1.16314301e-02 -1.46392127e-02
  3.29667702e-02  2.28550043e-02 -7.96253458e-02 -2.48320755e-02
  2.88208947e-02 -3.20719332e-02 -7.87956566e-02 -6.80825906e-03
  4.41509709e-02  3.72945890e-02 -8.20928439e-02 -1.81928072e-02
 -3.93603407e-02  3.98883782e-02  2.76136305e-02 -6.14577904e-04
 -4.51389961e-

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)  File "<ipython-input-50-64ce638f4971>", line 10, in <module>
    embeddings.write(0,result)  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 245, in wrapped
    error_in_function=error_in_function)
ERROR:tensorflow:=

tf.Tensor(
[ 0.00974628 -0.05949231  0.01470726 -0.0863429   0.05475954  0.02897093
  0.02571323 -0.02398274 -0.02819083  0.01086848 -0.01850961  0.03653141
  0.0182818  -0.01914504  0.12469097 -0.04278153 -0.0411514   0.04883203
  0.00376154 -0.0005638  -0.06991312 -0.06369539 -0.03897798 -0.0055684
  0.04505977 -0.01431632  0.02604888  0.00964377  0.00285145  0.03738635
 -0.09198706  0.01081256  0.01892822 -0.05538889  0.08077052 -0.06292091
 -0.01123279  0.05289828  0.04834101  0.013483   -0.00282621 -0.04336841
 -0.03977695  0.02537595  0.0188976  -0.00707675 -0.00232798 -0.06497371
 -0.02028891 -0.04834794 -0.0036282   0.02415116 -0.01068292 -0.04140424
  0.00082496 -0.04959113 -0.03896485  0.01788011  0.03556323  0.0286251
  0.039443   -0.00624254  0.03243814 -0.01677061  0.04002398 -0.02708676
 -0.01174368  0.00055634  0.03391292  0.01638767 -0.00278289  0.01450711
 -0.05441204  0.03099084  0.03563732 -0.01420268  0.00430248  0.00194838
 -0.02253431 -0.00641126  0.0367969  -0.01

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.ops.tensor_array_ops.TensorArray'>):
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)  File "<ipython-input-50-64ce638f4971>", line 10, in <module>
    embeddings.write(0,result)  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 245, in wrapped
    error_in_function=error_in_function)


tf.Tensor(
[ 5.32772280e-02 -4.55587022e-02  8.19604471e-03 -6.44541159e-02
  5.09206764e-02 -7.35339224e-02  3.04773659e-03 -4.05600108e-02
 -3.60104851e-02 -5.54719381e-02 -4.07539047e-02 -4.89074253e-02
  1.72561165e-02 -3.34558338e-02  4.53269742e-02  6.80100056e-04
  1.65544711e-02 -1.60089824e-02 -1.97091084e-02 -2.91748773e-02
 -2.33390015e-02 -1.37028657e-02 -6.92512188e-03 -3.23525965e-02
  3.30801532e-02  2.50285380e-02  1.61077715e-02  1.78410206e-02
 -1.03677325e-01 -5.95322344e-03 -5.01959212e-02 -9.03524738e-03
  5.26192971e-02 -3.26984003e-02 -9.15941224e-03 -1.09446518e-01
 -6.81101158e-02 -4.97875139e-02  2.20443737e-02  6.02079481e-02
  1.14528630e-02 -3.62761803e-02 -2.83641201e-02 -5.85538261e-02
  2.05865391e-02 -6.36158809e-02 -2.22964175e-02 -8.13204795e-03
  3.63187045e-02 -1.85456816e-02  2.66348012e-03 -6.08174689e-03
 -2.53820587e-02 -3.53035182e-02  2.87038181e-02 -6.81669787e-02
 -6.89025745e-02  3.09837442e-02  2.77426606e-03 -1.27973128e-02
  6.63829669e-

In [ ]:
# embeddings[0]

In [ ]:
type(embeddings)

tensorflow.python.ops.tensor_array_ops.TensorArray

In [ ]:
encoder = LabelEncoder()
intent = database['intent']
encodedintent = encoder.fit_transform(intent)
print(encodedintent)

[1 1 1 1 3 3 3 3 2 2 2 2 0 0 0 0]


In [ ]:
data = {'EmbMessage': embeddings,
        'EncodIntent': encodedintent}
  
# Create DataFrame
df = pd.DataFrame(data)
df

EmbMessage  EncodIntent
0   <tensorflow.python.ops.tensor_array_ops.Tensor...            1
1   <tensorflow.python.ops.tensor_array_ops.Tensor...            1
2   <tensorflow.python.ops.tensor_array_ops.Tensor...            1
3   <tensorflow.python.ops.tensor_array_ops.Tensor...            1
4   <tensorflow.python.ops.tensor_array_ops.Tensor...            3
5   <tensorflow.python.ops.tensor_array_ops.Tensor...            3
6   <tensorflow.python.ops.tensor_array_ops.Tensor...            3
7   <tensorflow.python.ops.tensor_array_ops.Tensor...            3
8   <tensorflow.python.ops.tensor_array_ops.Tensor...            2
9   <tensorflow.python.ops.tensor_array_ops.Tensor...            2
10  <tensorflow.python.ops.tensor_array_ops.Tensor...            2
11  <tensorflow.python.ops.tensor_array_ops.Tensor...            2
12  <tensorflow.python.ops.tensor_array_ops.Tensor...            0
13  <tensorflow.python.ops.tensor_array_ops.Tensor...            0
14  <tensorflow.python.ops.tensor_array_ops.Tensor...            0
15  <tensorflow.python.ops.tensor_array_ops.Tensor...            0

## **Decision Tree**

In [ ]:
RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(
    df,
    test_size=0.4,
    random_state=RANDOM_SEED,
)

In [ ]:
train_set

EmbMessage  EncodIntent
9   <tensorflow.python.ops.tensor_array_ops.Tensor...            2
2   <tensorflow.python.ops.tensor_array_ops.Tensor...            1
15  <tensorflow.python.ops.tensor_array_ops.Tensor...            0
4   <tensorflow.python.ops.tensor_array_ops.Tensor...            3
7   <tensorflow.python.ops.tensor_array_ops.Tensor...            3
10  <tensorflow.python.ops.tensor_array_ops.Tensor...            2
12  <tensorflow.python.ops.tensor_array_ops.Tensor...            0
3   <tensorflow.python.ops.tensor_array_ops.Tensor...            1
6   <tensorflow.python.ops.tensor_array_ops.Tensor...            3

In [ ]:
x_train = train_set['EmbMessage']
y_train = train_set['EncodIntent']

In [ ]:
 type(x_train)

pandas.core.series.Series

In [ ]:
# x_train[9]

In [ ]:
y_train

9     2
2     1
15    0
4     3
7     3
10    2
12    0
3     1
6     3
Name: EncodIntent, dtype: int64

In [ ]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier()
tree_clf.fit(x_train, y_train)

TypeError: ignored